name: Noderr Protocol CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  # Lint and Type Check
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install pnpm
      run: npm install -g pnpm@8
      
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run linter
      run: pnpm run lint
      
    - name: Type check
      run: pnpm run type-check

  # Unit Tests
  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        module: [
          'risk-engine',
          'market-intelligence',
          'execution-optimizer',
          'ai-core',
          'system-vanguard',
          'quant-research',
          'integration-layer',
          'telemetry-layer'
        ]
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install pnpm
      run: npm install -g pnpm@8
      
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run tests for ${{ matrix.module }}
      run: pnpm --filter @noderr/${{ matrix.module }} test
      
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./packages/${{ matrix.module }}/coverage/lcov.info
        flags: ${{ matrix.module }}

  # Build Docker Images
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    strategy:
      matrix:
        module: [
          'risk-engine',
          'market-intelligence',
          'execution-optimizer',
          'ai-core',
          'system-vanguard',
          'quant-research',
          'integration-layer',
          'telemetry-layer'
        ]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.module }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./packages/deployment/docker/Dockerfile.module
        build-args: |
          MODULE=${{ matrix.module }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Run Readiness Validator
  validate:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install pnpm
      run: npm install -g pnpm@8
      
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Build readiness validator
      run: pnpm --filter @noderr/readiness-validator build
      
    - name: Start test environment
      run: |
        docker-compose -f packages/deployment/docker/docker-compose.yaml up -d
        sleep 30  # Wait for services to start
        
    - name: Run validation
      run: pnpm --filter @noderr/readiness-validator validate:full
      
    - name: Stop test environment
      if: always()
      run: docker-compose -f packages/deployment/docker/docker-compose.yaml down

  # Deploy to Staging
  deploy-staging:
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: staging
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
        
    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.STAGING_KUBECONFIG }}" | base64 -d > $HOME/.kube/config
        
    - name: Deploy to staging
      run: |
        kubectl apply -f packages/deployment/kubernetes/namespace.yaml
        kubectl apply -f packages/deployment/kubernetes/configmap.yaml
        kubectl apply -f packages/deployment/kubernetes/secrets.yaml
        kubectl apply -f packages/deployment/kubernetes/deployment.yaml
        kubectl apply -f packages/deployment/kubernetes/service.yaml
        kubectl apply -f packages/deployment/kubernetes/ingress.yaml
        kubectl apply -f packages/deployment/kubernetes/hpa.yaml
        
    - name: Wait for rollout
      run: |
        kubectl -n noderr rollout status deployment/noderr-integration-layer
        kubectl -n noderr rollout status deployment/noderr-risk-engine
        kubectl -n noderr rollout status deployment/noderr-market-intelligence
        kubectl -n noderr rollout status deployment/noderr-execution-optimizer
        kubectl -n noderr rollout status deployment/noderr-ai-core
        kubectl -n noderr rollout status deployment/noderr-system-vanguard
        kubectl -n noderr rollout status deployment/noderr-quant-research
        kubectl -n noderr rollout status deployment/noderr-telemetry-layer

  # Deploy to Production
  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
        
    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.PRODUCTION_KUBECONFIG }}" | base64 -d > $HOME/.kube/config
        
    - name: Deploy to production
      run: |
        kubectl apply -f packages/deployment/kubernetes/namespace.yaml
        kubectl apply -f packages/deployment/kubernetes/configmap.yaml
        kubectl apply -f packages/deployment/kubernetes/secrets.yaml
        kubectl apply -f packages/deployment/kubernetes/deployment.yaml
        kubectl apply -f packages/deployment/kubernetes/service.yaml
        kubectl apply -f packages/deployment/kubernetes/ingress.yaml
        kubectl apply -f packages/deployment/kubernetes/hpa.yaml
        
    - name: Wait for rollout
      run: |
        kubectl -n noderr rollout status deployment/noderr-integration-layer
        kubectl -n noderr rollout status deployment/noderr-risk-engine
        kubectl -n noderr rollout status deployment/noderr-market-intelligence
        kubectl -n noderr rollout status deployment/noderr-execution-optimizer
        kubectl -n noderr rollout status deployment/noderr-ai-core
        kubectl -n noderr rollout status deployment/noderr-system-vanguard
        kubectl -n noderr rollout status deployment/noderr-quant-research
        kubectl -n noderr rollout status deployment/noderr-telemetry-layer
        
    - name: Run post-deployment validation
      run: |
        kubectl -n noderr exec deployment/noderr-integration-layer -- npm run validate

  # Notify on failure
  notify:
    runs-on: ubuntu-latest
    needs: [lint, test, build, validate, deploy-staging, deploy-production]
    if: failure()
    steps:
    - name: Send Slack notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: 'Noderr Protocol CI/CD pipeline failed!'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        
    - name: Create GitHub issue
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `CI/CD Pipeline Failed - ${context.sha.substring(0, 7)}`,
            body: `The CI/CD pipeline failed for commit ${context.sha}.\n\nWorkflow: ${context.workflow}\nRun: ${context.runId}`,
            labels: ['bug', 'ci/cd']
          }) 